version: '3'

services:
  burp-client:
    image: strangefog/burp-client:arm32v7
    hostname: burp-client
    volumes:
      - burp-client-conf:/etc/burp
      - /etc:/tobackup/burp-client-etc:ro
    security_opt:
      - label:disable
    environment:
      - BURP_CLIENT_PASSWORD=super-secret
    networks:
      - burp

networks:
  burp:

volumes:
  burp-client-conf:
